# .overcommit.yml
PreCommit:
  RuboCop:
    enabled: true
    description: 'Auto-corrigindo código com RuboCop antes do commit'
    flags: [ '--auto-correct', '--fail-level', 'E' ]
    require_executable: [ 'bundle', 'exec', 'rubocop' ]
    on_warn: fail

  RSpec:
    enabled: true
    command: [ 'bundle', 'exec', 'rspec' ]
    description: 'Executando testes automatizados'

CommitMsg:
  CommitMessageFormat:
    enabled: true
    required_pattern: '^(feat|fix|chore|refactor|docs|test|style|perf|ci): .+'
    error_message: 'Commit deve começar com feat:, fix:, chore:, etc.'

